// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();
const path = require("path"); 
const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
  });


  const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, "uploads/"),
  filename: (req, file, cb) => {
    cb(null, Date.now() + path.extname(file.originalname));
  },
});

const upload2 = multer({ storage });


router.post("/login", dataController.login);
router.post("/forgetPassword", dataController.forgetPassword);
router.post('/verify-otp', dataController.verifyOtp);
router.post("/signup", dataController.signUp);
router.post("/city", dataController.getCity)
router.post("/variant", dataController.getvariant)
router.post("/uom", dataController.getuom)
router.post("/country", dataController.getCountry)
router.post("/state", dataController.getState)
router.post("/status", dataController.getStatus)
router.post("/Shift", dataController.getShift)
router.post("/Transaction", dataController.getTransaction)
router.post("/gender", dataController.getGender)
router.post("/Loginorout", dataController.getLoginorout)
router.get("/", dataController.getAllData)
router.post("/add", upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.addData)
router.post("/useradd",upload.single('user_img'),dataController.userAddData)
router.get ("/userData", dataController.getAlluserData)
router.get("/WareHouseData",dataController.getAllWareHouseData)
router.post("/AddWareHousedata",dataController.AddWareHouseData)
router.get("/RoleInfoData", dataController.getAllRoleInfoData)
router.post("/addRoleInfoData", dataController.AddRoleInfoData)
router.post("/Roleupdate", dataController.RolesaveEditedData)
router.post("/saveEditedData", dataController.saveEditedData);
router.post("/delete", dataController.deleteData);
router.post("/userdelete", dataController.UserdeleteData)
router.post("/userupdate", dataController.UsersaveEditedData)
router.post("/warehouseupdate", dataController.WareHousesaveEditedData)
router.get("/attrihdrdata",dataController.getAllattributehdrData)
router.post("/addattriData",dataController.addattrihdrData)
//router.post("/updattriData",dataController.updattrihdrData)
router.get("/attributedetData",dataController.getAllattributedetData)
router.post("/addattridetData",dataController.addattridetData)
router.post("/updattridetData",dataController.updattridetData)
router.post("/delattridetData",dataController.deleteAttriDetailData)
router.get("/hdrcode", dataController.gethdrcode)
router.get("/IntermediaryheaderData", dataController.getAllIntermediaryheaderData)
router.post("/AddIntermediaryheaderData", dataController.addIntermediaryHdrData)
router.get("/IntermediarydetailData", dataController.getAllIntermediaryDetailData)
router.post("/addIntermediaryDetailData", dataController.addIntermediaryDetailData)
router.post("/updateIntermediaryDetailData", dataController.updintermediarydetData)
router.post("/deleteIntermediaryHeaderData", dataController.deleteIntermediaryHeaderData)
router.post("/deleteIntermediaryDetailData", dataController.deleteIntermediaryDetailData)
router.post("/delPer", dataController.getDeletepermission)
router.post("/regbrand", dataController.getregisterbrand)
router.post("/ourbrand", dataController.getourbrand)
router.get("/inthdrcode", dataController.getInthdrcode)
router.post("/companysearchcriteria",dataController.getsearchdata)
router.post("/warehousedelete",dataController.WareHousedeleteData)
router.get("/VendorHdrData",dataController.getAllVendorHdrData)
router.post("/addVendorHdrData",dataController.addVendorHdrData)
router.get("/VendorDetData", dataController.getAllVendorDetData)
router.post("/addVendorDetData",dataController.addVendorDetData)
router.post("/updvendordetData",dataController.updvendordetData)
router.post("/deleteVendorData",dataController.VendordeleteData)
router.post("/vendorcode",dataController.getvendorcode)
router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
router.get("/usercode",dataController.getUsercode)
router.post("/Usertype", dataController.getUsertype)
router.get("/Companyno",dataController.getCompanyno)
router.get("/locationno",dataController.getLocationno)
router.post("/paytype", dataController.getPaytype)
router.post("/purchasetype", dataController.getPurchasetype)
router.post("/salestype", dataController.getSalestype)
router.post("/ordertype", dataController.getordertype)
router.post("/vendorcodename", dataController.getVendorcodename)
router.post("/roleid", dataController.getroleid)
router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
router.post("/warehouseSearchdata",dataController.getwarehouseSearchdata)
router.post("/locationSearchdata",dataController.getlocationsearchdata)
router.post("/addlocationinfo",dataController.addlocationinfo)
router.post("/location_no",dataController.locationsaveEditedData)
router.post("/deletelocation",dataController.locationdeleteData)
router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
router.post("/usersearchcriteria",dataController.getUsersearchdata)
router.post("/Rolesearchdata",dataController.getRolesearchdata)
router.post("/roledelete",dataController.roledeleteData)
router.post("/vendorsearchdata",dataController.getvendorSearchdata)
router.post("/PartyCode",dataController.getPartyCode)
router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
router.post("/attributeSearchdata",dataController.getattributeSearchdata)
router.post("/intermediarySearchdata",dataController.getintermediarySearchdata)
router.get("/smcode",dataController.getsalesmancode)
router.get("/trcode",dataController.gettransportcode)
router.get("/brcode",dataController.getbrokercode)
router.post("/transactiontype",dataController.gettranstype)
router.post("/getPurchaseData",dataController.getPurchaseData)
router.post("/getpurchasereturnit",dataController.getpurchasereturnit)
router.post("/getpurchasereturntax",dataController.getpurchasereturntax)
router.get("/Numberseries",dataController.getAllNumberseries)
router.post("/addNumberseries",dataController.addNumberseries)
router.post("/numberseriessearchdata",dataController.getnumberseriessearchdata)
router.post("/saveEditedNumberseriesData",dataController.saveEditedNumberseriesData)
router.post("/screentype",dataController.getscreentype)
router.post("/numberseriesdeleteData",dataController.numberseriesdeleteData)
router.post("/onlywarehsearchdata",dataController.getonlywarehsearchdata)
router.post("/getusercompany",dataController.getusercompany)
router.post("/updcompanymapping",dataController.updcompanymapping)
router.post("/commappingdeleteData",dataController.commappingdeleteData)
router.post("/getSalesData",dataController.getSalesData)
router.post("/getSalesDetail",dataController.getSalesDetail)
router.post("/getSalesTaxDetail",dataController.getSalesTaxDetail)
router.post("/getWarehouseCodeData",dataController.getWarehouseCodeData)
router.get("/userscreenmap", dataController.getAlluserscreenmap)
router.post("/adduserscreenmap",dataController.adduserscreenmap)
router.post("/saveEditeduserscreenmap",dataController.saveEditeduserscreenmap)
router.post("/userscreenmapdeleteData",dataController.userscreenmapdeleteData)
router.post("/userscreensearchdata",dataController.getuserscreensearchdata)
router.post("/Screens",dataController.getScreens)
router.post("/Permissions",dataController.getPermissions)
router.post("/getUserPermission",dataController.getUserPermission)
router.post("/getPurchaseDeleteDetails", dataController.getPurchaseDeleteDetails)
router.post("/purdeletedunit", dataController.purdeletedunit)
router.post("/purdeletedtax", dataController.purdeletedtax)
router.post("/getRefSalesDelete", dataController.getRefSalesDelete);
router.post("/saledelsearchitem", dataController.saledelsearchitem);
router.post("/salesdelsearchtax", dataController.salesdelsearchtax);
router.post("/addBaseaccountData",dataController.addBaseaccountData)
router.get("/getAllBaseAccountData",dataController.getAllBaseAccountData)
router.post("/getsearchdataBase",dataController.getsearchdataBase)
router.post("/updateBase",dataController.updateBase)
router.post("/deleteBaseData",dataController.deleteBaseData)
router.post("/addUserAccGrp",dataController.addUserAccGrp)
router.post("/getsearchUserAccGrp", dataController.getsearchUserAccGrp);
router.post("/updUserAccGrp", dataController.updUserAccGrp);
router.post("/deleteUserAccGrp",dataController.deleteUserAccGrp)
router.get("/getStdAccGrp",dataController.  getStdAccGrp)
router.get("/getBaseAccGrp",dataController.  getBaseAccGrp)
router.post("/AddStandardAccountData",dataController.addstandardaccountData)
router.get("/getAllStandardAccountData",dataController.getAllStandardAccountData)
router.get("/getbasaccode",dataController.getbasaccode)
router.post("/getstandardsearchdata",dataController.getstandardsearchdata)
router.post("/deleteStdAccGrp",dataController.deleteStdAccGrp)
router.post("/updStdAccGrp",dataController.updStdAccGrp)
router.post("/getpurchasereturnView",dataController.getpurchasereturnView)
router.post("/getSalesreturnView",dataController.getSalesreturnView)
router.post("/getwarehousedrop",dataController.getwarehousedrop)
router.post("/addAccountName",dataController.addAccountName)
router.post("/getAccNameSearch",dataController.getAccNameSearch)
router.post("/updateAccName",dataController.updateAccName)
router.post("/AccNameDelete",dataController.AccNameDelete)
router.get("/AllAccNameData",dataController.getAllAccNameData)
router.post("/SalesReturnTaxView",dataController.SalesReturnTaxView)
router.post("/SalesReturnDetailView",dataController.SalesReturnDetailView)
router.post("/getpurchasereturntaxView",dataController.getpurchasereturntaxView)
router.post("/getpurchasereturnitView",dataController.getpurchasereturnitView)
router.post("/getUsercodename",dataController.getUsercodename)
router.post("/getAccountCode",dataController.getAccountCode)
router.post("/addbankAccount",upload.single('bank_paymentQRCode'),dataController.addbankAccount)
router.post("/getacctype",dataController.getacctype)
router.post("/updatebankAcc",dataController.updatebankAcc)
router.post("/getbankaccSearch",dataController.getbankaccSearch)
router.post("/getofftype",dataController.getofftype)
router.post("/getItem",dataController.getItem) 
router.post("/getDcDetailView",dataController.getDcDetailView) 
router.post("/getQuotationDetailView",dataController.getQuotationDetailView) 
router.post("/getQuotationTaxDetailView",dataController.getQuotationTaxDetailView) 
router.post("/getPODetailView",dataController.getPODetailView) 
router.post("/getPOTaxDetailView",dataController.getPOTaxDetailView) 
router.post("/getQuotation",dataController.getQuotation) 
router.post("/getDeliveryChallan",dataController.getDeliveryChallan) 
router.post("/getPurchaseOrder",dataController.getPurchaseOrder) 
router.post("/RollMappingDelete",dataController.RollMappingDelete)
router.post("/updateRoleMapping",dataController.updateRoleMapping)
router.post("/UserRole",dataController.getUserRole)
router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
router.post("/AddDepartment",dataController.AddDepartment)
router.get("/ViewEmployee",dataController.ViewEmployee)
router.post("/getInventoryTransaction",dataController.getInventoryTransaction)
router.post("/getInventoryReturn",dataController.getInventoryReturn)
router.post("/getInventoryReturnDetails",dataController.getInventoryReturnDetails)
router.post("/getInventoryReceipt",dataController.getInventoryReceipt)
router.post("/getInventoryReceiptDetail",dataController.getInventoryReceiptDetail)
router.post("/getInventoryIssued",dataController.getInventoryIssued)
router.post("/getInventoryIssuedDetail",dataController.getInventoryIssuedDetail)
router.post("/getallAssetsAllocation",dataController.getallAssetsAllocation)
router.post("/getEmptype", dataController.getEmptype)
router.post("/getDept", dataController.getDept)
router.post("/getDesgination", dataController.getDesgination)
router.post("/ProductData", dataController.getProductData)
router.post("/ProductDetail", dataController.getProductDetail)
router.post("/getallassetsdetails", dataController.getallassetsdetails)
router.post("/Condition", dataController.getCondition)
router.post("/AddDesgination", dataController.AddDesgination)
router.get("/GetAllDesgination", dataController.GetAllDesgination)
router.post("/desginationDelete", dataController.desginationDelete)
router.post("/UpdateDesgintion", dataController.DesgintionEditData)
router.post("/DesginationSerachData", dataController.desgsearch)
router.post("/DepartmentSerachData", dataController.DeptSearch)
router.post("/UpdateDepartment", dataController.DepartmetEditData)
router.post("/DeleteDepartment", dataController.departmentDelete)
router.post("/LocationUpdate", dataController.LocationUpdate)
router.post("/CompanyUpdate",upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.CompanyUpdate)
router.post("/UpdateCompanyImage",upload.single('company_logo'),dataController.UpdateCompanyImage)
router.post("/RoleUpdates", dataController.RoleUpdate)
router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
router.post("/AttributeUpdate", dataController.AttributeUpdate)
router.post("/NumberSeriesUpdate", dataController.NumberSeriesUpdate)
router.post("/WarehouseUpdates", dataController.WarehouseUpdate)
router.post("/VendorUpdate", dataController.VendorUpdate)
router.post("/IntermediaryUpdate", dataController.IntermediaryUpdate)
router.post("/BankAccountUpdate",upload.single('bank_paymentQRCode'), dataController.BankAccountUpdate)
router.post("/DepartmentUpdate",dataController.DepartmentUpdate)
router.post("/DesgintionUpdate",dataController.DesgintionUpdate)
router.post("/BaseAccountUpdate",dataController.BaseAccountUpdate)
router.post("/COAUpdate",dataController.COAUpdate) // charts of Accounts
router.post("/StandardAccUpdate",dataController.StandardAccUpdate) 
router.post("/UserAccGrpUpdate",dataController.UserAccGrpUpdate) 
router.post("/getadjustmentdata",dataController.getadjustmentdata)
router.post("/OpeningBalance",dataController.getOpeningBalance)
router.post("/OpeningBalanceDetails",dataController.getOpeningBalanceDetails)
router.post("/AdjustmentDetails",dataController.getAdjustmentDetails)
router.post("/getJournaldata",dataController.getJournaldata)
router.post("/getJournalDetails",dataController.getJournalDetails)
router.post("/getEvent", dataController.getEvent)
router.post("/getTaxInvoiceTax",dataController.getTaxInvoiceTax)  
router.post("/gettaxinvoiceDetail",dataController.gettaxinvoiceDetail) 
router.post("/addEmployeeLoan",dataController.addEmployeeLoan) 
router.post("/getEmployeeLoan",dataController.getEmployeeLoan) 
router.get("/getsearchEmpLoan",dataController.getsearchEmpLoan) 
router.post("/deleteEmployeeLoan",dataController.deleteEmployeeLoan) 
router.post("/updateEmployeeLoan",dataController.updateEmployeeLoan) 
router.get("/getApprovedBy",dataController.getApprovedBy) 
router.post("/addGrade",dataController.addGrade)
router.get("/allGradeData",dataController.allGradeData)
router.post("/deleteGrade",dataController.deleteGrade)
router.post("/updateGrade",dataController.updateGrade)
router.post("/addEmployeeCompany",dataController.addEmployeeCompany)
router.get("/allEmployeeCompanyData",dataController.allEmployeeCompanyData)
router.post("/deleteEmployeeCompany",dataController.deleteEmployeeCompany)
router.post("/updateEmployeeCompany",dataController.updateEmployeeCompany)
router.post("/addEmployeeFamily",dataController.addEmployeeFamily)
router.get("/allEmployeeFamilyData",dataController.allEmployeeFamilyData)
router.post("/deleteEmployeeFamily",dataController.deleteEmployeeFamily)
router.post("/updateEmployeeFamily",dataController.updateEmployeeFamily)
router.post("/addSalaryDetails",dataController.addSalaryDetails)
router.get("/allSalaryDetailsData",dataController.allSalaryDetailsData)
router.post("/deleteSalaryDetails",dataController.deleteSalaryDetails)
router.post("/updateSalaryDetails",dataController.updateSalaryDetails)
router.post("/addEmployeeLeave",dataController.addEmployeeLeave)
router.get("/allEmployeeLeaveData",dataController.allEmployeeLeaveData)
router.post("/deleteEmployeeLeave",dataController.deleteEmployeeLeave)
router.post("/updateEmployeeLeave",dataController.updateEmployeeLeave)
router.post("/addEmployeedoc", upload.fields([
  { name: 'ResumeFile', maxCount: 1 },
  { name: 'OfferLetter', maxCount: 1 },
  { name: 'JoiningLetter', maxCount: 1 },
  { name: 'ContractAndAgreement', maxCount: 1 },
  { name: 'aadhar_and_pan', maxCount: 1 }
]), dataController.addEmployeedoc);
router.post("/delemployeedoc",dataController.delemployeedoc)
router.post("/delemployeedoc",dataController.delemployeedoc)
router.get("/getAllemployeedoc",dataController.getAllemployeedoc)
router.post("/UpdateEmployeeImage",upload.single('Photos'),dataController.UpdateEmployeeImage)
router.post("/Employeedataupdate",upload.single('Photos'),dataController.Employeedataupdate)
router.post("/deleteemployeedata",dataController.  deleteemployeeper)
router.get("/getAllemployeedata",dataController.getAllemployeedata)
router.post("/getEmployeeDocument",dataController.getEmployeeDocument)
router.post("/addEmployeePersonalData", upload.single('Photos'),dataController.addEmployeePersonalData) 
router.post("/getID",dataController.getID) 
router.post("/getsiblings",dataController.getsiblings)
router.post("/getKids",dataController.getkids)
router.post("/getMartial",dataController.getMartial)
router.post("/addLeaveType",dataController.addLeaveType)
router.get("/getemployeemanager",dataController.getemployeemanager)
router.post("/getEmployeeFamily",dataController.getEmployeeFamily)
router.post("/getSalaryType",dataController.getSalaryType)
router.post("/getPayscale",dataController.getPayscale)
router.post("/Add_employee_bankdetails",dataController.Add_employee_bankdetails)
router.post("/Employeebankdetdelete",dataController.Employeebankdetdelete)
router.post("/updateEmployeebankdet",dataController.updateEmployeebankdet)
router.get("/getallEmployeebankdet",dataController.getallEmployeebankdet)
router.post("/getEmployeeSalary",dataController.getEmployeeSalary)
router.post("/getGrade", dataController.getGrade)
router.post("/getEmployeeBankDeatils",dataController.getEmployeeBankDeatils)
router.post("/getEmployeePersonaldet",dataController.getEmployeePersonaldet)
router.post("/getLoanID",dataController.getLoanID)
router.post("/getTaxInvoiceNo",dataController.getTaxInvoiceNo)
router.post("/addEmployeeAcademicDetails",dataController.addEmployeeAcademicDetails)
router.get("/allEmployeeAcademicDetails",dataController.allEmployeeAcademicDetails)
router.post("/updateEmployeeAcademicDetails",dataController.updateEmployeeAcademicDetails)
router.post("/deleteEmployeeAcademicDetails",dataController.deleteEmployeeAcademicDetails)
router.post("/addEmployeeIdentityDocument",dataController.addEmployeeIdentityDocument)
router.get("/allEmployeeIdentityDocument",dataController.allEmployeeIdentityDocument)
router.post("/updateEmployeeIdentityDocument",dataController.updateEmployeeIdentityDocument)
router.post("/deleteEmployeeIdentityDocument",dataController.deleteEmployeeIdentityDocument)
router.post("/getDocumentType",dataController.getDocumentType)
router.post("/getAcademicDetails",dataController.getAcademicDetails)
router.post("/getallProduct",dataController.getallProduct)
router.post("/getrelation",dataController. getrelation)
router.post("/getannoncementtype",dataController. getannoncementtype)
router.post("/getAnnouncementDetail",dataController. getAnnouncementDetail)
router.post("/getAnnouncement_Msg",dataController. getAnnouncement_Msg)
router.post("/getallOpeningItem",dataController.getallOpeningItem)
router.post("/getallOpeningItemDetail",dataController.getallOpeningItemDetail)
router.post("/addAnnounmentdetails",dataController.addAnnounmentdetails)
router.post("/deleteAnnouncement",dataController.deleteAnnouncement)
router.get("/allAnnouncementDetails",dataController.allAnnouncementDetails)
router.post("/updateAnnouncementDetails",dataController.updateAnnouncementDetails)
router.get("/getAnnouncementDetail",dataController.getAnnouncement)
router.post("/EmployeePersonalSC",dataController.EmployeePersonalSC)
router.post("/getAnnouncementDetails",dataController.getAnnouncementDetails)
router.post("/getcompanyshift",dataController.getcompanyshift)
router.post("/LeaveStatus",dataController.DashboardLeaveStatus)
router.post("/UpcomingBirthday",dataController.DashboardUpcomingBirthday)
router.post("/NewJoinee",dataController.DashboardNewJoinee)
router.post("/OverallAttendance",dataController.DashboardOverallAttendance)
router.post("/TeamList",dataController.DashboardTeamList)
router.post("/TeamListChart",dataController.DashboardTeamListChart)
router.post("/LeaveAuthorization",dataController.DashboardLeaveAuthorization)
router.post("/getEmpcompanyDetails",dataController.getEmpcompanyDetails)
router.post("/getOverallTAX",dataController.getOverallTAX)
router.post("/getAcademicDetailsSearchCretria",dataController.getAcademicDetailsSearchCretria)
router.post("/getIdentityDocuments",dataController.getIdentityDocuments)
router.post("/getTeamManager",dataController.getTeamManager)
router.post("/EmployeeCompanyISC",dataController. EmployeeCompanyISC)
router.post("/getInvocieType",dataController.getInvocieType)
router.post("/gettermsdc",dataController.gettermsdc)
router.post("/getQuotationTCDetailView",dataController.getQuotationTCDetailView)
router.post("/getPOTCDetailView",dataController.getPOTCDetailView)
router.post("/getTITerms",dataController.getTITerms)
router.post("/getUsercodenameBank",dataController.getUsercodenameBank)
router.post("/getVendorDetails",dataController.getVendorDetails)
router.post("/getIdentityDocumentSearchCretria",dataController.getIdentityDocumentSearchCretria)
router.post("/getFinancialDetailsSearchCretria",dataController.getFinancialDetailsSearchCretria)
router.post("/getFamilyDetailsSearchCretria",dataController.getFamilyDetailsSearchCretria)
router.post("/Terms",dataController.TermsDC)
router.post("/TermsQO",dataController.TermsQO)
router.post("/TermsPO",dataController.TermsPO)
router.post("/TermsTI",dataController.TermsTI)
router.post("/getEmpBankDetailsSC",dataController.getEmpBankDetailsSC)
router.post("/getESSmanager",dataController.getESSmanager)
router.post("/getLeaveType",dataController.getLeaveType)
router.post("/getSelectSlot",dataController.getSelectSlot)
router.post("/getDashBoardType",dataController.getDashBoardType)
router.post("/getGSTReport",dataController.getGSTReport)
router.post("/getDeletedDeliveryChallan",dataController.getDeletedDeliveryChallan)
router.post("/getDeletedDcDetailView",dataController.getDeletedDcDetailView)
router.post("/getDeletedDcTerms",dataController.getDeletedDcTerms)
router.post("/getDeletedPurchaseOrder",dataController.getDeletedPurchaseOrder)
router.post("/getDeletedPoDetail",dataController.getDeletedPoDetail)
router.post("/getDeletedPoTaxDetail",dataController.getDeletedPoTaxDetail)
router.post("/getDeletedPoTerms",dataController.getDeletedPoTerms)
router.post("/getDeletedQuotation",dataController.getDeletedQuotation)
router.post("/getDeletedQuotationTaxDetailView",dataController.getDeletedQuotationTaxDetailView)
router.post("/getDeletedQuotationDetailView",dataController.getDeletedQuotationDetailView)
router.post("/getDeletedQuotationTerms",dataController.getDeletedQuotationTerms)
router.post("/getDeletedTaxInvoice",dataController.getDeletedTaxInvoice)
router.post("/getDeletedTaxInvoiceTax",dataController.getDeletedTaxInvoiceTax)
router.post("/getDeletedTaxinvoiceDetail",dataController.getDeletedTaxinvoiceDetail)
router.post("/getDeletedTaxIvoiceTerms",dataController.getDeletedTaxIvoiceTerms)
router.post("/getType",dataController.getType)
router.post("/getAccrual",dataController.getAccrual)
router.post("/getExceedLeave",dataController.getExceedLeave)
router.post("/getLeaveReason",dataController.getLeaveReason)
router.post("/getAnnouncement",dataController.getAnnouncement)
router.post("/EmployeeDashboardNewJoinee",dataController.EmployeeDashboardNewJoinee)
router.post("/EmployeeDashboardUpcomingBirthday",dataController.EmployeeDashboardUpcomingBirthday)
router.post("/EmployeeDashboardTotalLeave",dataController.EmployeeDashboardTotalLeave)
router.post("/addEmployeeHoliday",dataController.addEmployeeHoliday)
router.get("/allEmployeeHoliday",dataController.allEmployeeHoliday)
router.post("/updateEmployeeHoliday",dataController.updateEmployeeHoliday)
router.post("/getsearchLeavetypes",dataController.getsearchLeavetypes)
router.post("/getLeaveTypeSearch",dataController.getLeaveTypeSearch)
router.post("/getPendingStatus",dataController.getPendingStatus)
router.post("/getsearchHoliday",dataController.getsearchHoliday)
router.post("/AddBonusDetails",dataController.AddBonusDetails)
router.post("/DelBonusDetails",dataController.DelBonusDetails)
router.post("/UpdBonusDetails",dataController.UpdBonusDetails)
router.post("/GetBonusDetails",dataController.GetBonusDetails)
router.post("/addTDS",dataController.addTDS)
router.post("/updateTDS",dataController.updateTDS)
router.get("/allTDS",dataController.allTDS)
router.post("/deleteTDS",dataController.deleteTDS)
router.post("/SearchTDS",dataController.SearchTDS)
router.post("/allProfessionalTax",dataController.allProfessionalTax)
router.post("/addProfessionalTax",dataController.addProfessionalTax)
router.post("/updateProfessionalTax",dataController.updateProfessionalTax)
router.post("/deleteProfessionalTax",dataController.deleteProfessionalTax)
router.post("/addLoanType",dataController.addLoanType)
router.post("/updateLoanType",dataController.updateLoanType)
router.get("/allLoanType",dataController.allLoanType)
router.post("/deleteLoanType",dataController.deleteLoanType)
router.post("/addPfDetails",dataController.addPfDetails)
router.post("/updatePfDetail",dataController.updatePfDetail)
router.post("/allPfDetail",dataController.allPfDetail)
router.post("/deletePfDetail",dataController.deletePfDetail)
router.post("/ProfessionalTaxSC",dataController.ProfessionalTaxSC)
router.post("/BonusDetails",dataController.getBonusDetails)
router.post("/getPFContribution",dataController.getPFContribution)
router.post("/getLoanType",dataController.getLoanType)
router.post("/getdefCustomer",dataController.getdefCustomer)
router.post("/getSalesMode",dataController.getSalesMode)
router.post("/getPurchaseAnalysis",dataController.getPurchaseAnalysis)
router.post("/addProject",dataController.addProject)
router.post("/updateProject",dataController.updateProject)
router.post("/deleteProject",dataController.deleteProject)
router.get("/getAllProject",dataController.getAllProject)
router.post("/addTask", upload.single('Documents'),dataController.addTask)
router.post("/updateTask",dataController.updateTask)
router.get("/getAllTask",dataController.getAllTask)
router.post("/addDailyLogin",dataController.addDailyLogin)
router.post("/addDailyTask", upload.array('Files', 10), dataController.addDailyTask);
router.post("/delDailyTask",dataController.delDailyTask)
router.post("/getTaskstatus",dataController.getTaskstatus)
router.get("/getDailyTasks",dataController.getDailyTasks)
router.post("/DailytaskSC",dataController.DailytaskSC)
router.post("/updateTask",dataController.updateTask)
router.post("/DeleteTask",dataController.DeleteTask)
router.post("/PendingCustomer",dataController.PendingCustomer)
router.post("/updateBankAccount",upload.single('bank_paymentQRCode'),dataController.updateBankAccount)
router.post("/projectSC",dataController.projectSC)
router.post("/getProjectTask",dataController.getProjectTask)
router.post("/getDailyTask",dataController.getDailyTask)
router.post("/getPriority",dataController.getPriority)
router.post("/getProjectDetail",dataController.getProjectDetail)
router.post("/getTaskDetail",dataController.getTaskDetail)
router.post("/addProjectMapping",dataController.addProjectMapping)
router.post("/updateProjectMapping",dataController.updateProjectMapping)
router.post("/deleteProjectMapping",dataController.deleteProjectMapping)
router.post("/getProjectDrop",dataController.getProjectDrop)
router.post("/getProjectMapping",dataController.getProjectMapping)
router.post("/getTaskDetailReport",dataController.getTaskDetailReport)
router.post("/getTaskHourReport",dataController.getTaskHourReport)
router.post("/getTaskHourReportDetail",dataController.getTaskHourReportDetail)
router.post("/Getmanager",dataController.Getmanager)
router.post("/getProjectDetailReport",dataController.getProjectDetailReport)
router.get("/getProjectReport",dataController.getProjectReport)
router.post("/GradeSC",dataController.GradeSC)
router.post("/LoanSC",dataController.LoanSC)
router.post("/TaskMasterSC",dataController.TaskMasterSC)
router.post("/Userdropdown",dataController.Userdropdown)
router.post("/deleteLeave",dataController.deleteLeave)
router.post("/UpdateLeaveType",dataController.UpdateLeaveType)
router.post("/AnnouncementSearchCretria",dataController.AnnouncementSearchCretria)
router.post("/Getticketandproject",dataController.Getticketandproject)
router.post("/GetProject",dataController.GetProject)
router.post("/DailyLogin",dataController.DailyLogin)
router.post("/DailyLogOUT",dataController.DailyLogOUT)
router.post("/Projectusercode",dataController.Projectusercode)
router.post("/deleteEmployeeHoliday",dataController.deleteEmployeeHoliday)
router.post("/EmpSearch",dataController.EmpSearch) //Dashboard Employee Search
router.post("/getAnnouncementDuration",dataController.getAnnouncementDuration)
router.post("/AddFileAttachment", upload.array('Files', 10), dataController.AddFileAttachment);
router.post("/ESSManager",dataController.ESSManager)
router.post("/GetClr",dataController.GetClr)
router.post("/getfiles",dataController.getfiles)
router.post("/getprojectSC",dataController.getprojectSC)
router.post("/PMSDashboard",dataController.PMSDashboard)
router.post("/getHolidayDate",dataController.getHolidayDate)
router.post("/PMSEmployeechart",dataController.PMSEmployeechart)
router.post("/AddSalaryCriteria",dataController.AddSalaryCriteria)
router.post("/DeleteSalaryCriteria",dataController.DeleteSalaryCriteria)
router.post("/UpdateSalaryCriteria",dataController.UpdateSalaryCriteria)
router.post("/GeneratePaySlip",dataController.GeneratePaySlip)
router.post("/GetPaysllipSC",dataController.GetPaysllipSC)
//router.post("/AddSearchCriteria", dataController.AddSearchCriteria)
router.post("/getboolean", dataController.getboolean)
router.post("/mailgenerating", dataController.mailgenerating)
router.post("/savePdf", upload.single("pdf"), dataController.savePDFToPath);
router.post("/GetPaysllipTemplate", dataController.GetPaysllipTemplate)
router.post("/sendPayslipEmails", dataController.sendPayslipEmails)
router.post("/salarySearchoption", dataController.salarySearchoption)
router.post("/UpdateSalary", dataController.UpdateSalary)
router.post("/salaryDelete", dataController.salaryDelete)
router.post("/AddEmpDoc",dataController.AddEmpDoc)
router.post("/delempdoc",dataController.delempdoc)
router.post("/getAllempdoc",dataController.getAllempdoc)
router.post("/getDocument",dataController.getDocument)
router.post("/getempdoc",dataController.getempdoc)
router.post("/getapplyLeavetype",dataController.getapplyLeavetype)
router.post("/updateempDoc",dataController.updateempDoc)
router.post("/getEmployeeTotalLeaveBalance",dataController.getEmployeeTotalLeaveBalance)
router.post("/getEmployeeLeavesearch",dataController.getEmployeeLeavesearch)
router.post("/sendAutoMail",dataController.sendAutoMail)
router.post("/getallAssetsAllocationReturn",dataController.getallAssetsAllocationReturn)
router.post("/getAssertReturnDetail",dataController.getAssertReturnDetail)
router.post("/assetsEmployeeId",dataController.assetsEmployeeId)
router.post("/updateRoleRights",dataController.updateRoleRights)
router.post("/termsandCondition",dataController.termsandCondition)
router.post("/getTermsandConditionSales",dataController.getTermsandConditionSales)
router.post("/getDeletedTermsSales",dataController.getDeletedTermsSales)
router.post("/AddFinacnialyearlockscreen",dataController.AddFinacnialyearlockscreen)
router.post("/deleteFinacnialyearlockscreen",dataController.deleteFinacnialyearlockscreen)
router.post("/SelectFinacnialyearlockscreen",dataController.SelectFinacnialyearlockscreen)
router.post("/UpdateFinacnialyearlockscreen",dataController.UpdateFinacnialyearlockscreen)
router.post("/deleteFinacnialyearlockscreenGrid",dataController.deleteFinacnialyearlockscreenGrid)
router.post("/getFinacnialyearlockscreenSearchCriteria",dataController.getFinacnialyearlockscreenSearchCriteria)
router.post("/getLockType", dataController.getLockType)
router.post("/vendorCodeDropdown",dataController.vendorCodeDropdown)
router.post("/UpdateFinacnialyearlock",dataController.UpdateFinacnialyearlock)
router.post("/TotalActiveEmployees",dataController.TotalActiveEmployees)
router.post("/TotalNetEarnings",dataController.TotalNetEarnings)
router.post("/TotalPayslips",dataController.TotalPayslips)
router.post("/EmployeeDocSC",dataController.EmployeeDocSC)
router.post("/AddPrintTemplate", dataController.AddPrintTemplate)
router.post("/Templatesearch",dataController.Templatesearch)
router.post("/getPrint",dataController.getPrint)
router.post("/getcopies",dataController.getcopies)
router.post("/WeekOff",dataController.WeekOff)
router.post("/GenerateEmployee",dataController.GenerateEmployee)
router.post("/openingTicketSearch",dataController.openingTicketSearch)
router.post("/getUserCode",dataController.getUserCode)
router.post("/AddWeekOff",dataController.AddWeekOff)
router.post("/deleteWeekOff",dataController.deleteWeekOff)
router.post("/updateWeekOff",dataController.updateWeekOff)
router.post("/getWeekOff",dataController.getWeekOff)
router.post("/AddGenerateEmployee",dataController.AddGenerateEmployee)
router.post("/deleteGenerateEmployee",dataController.deleteGenerateEmployee)
router.post("/getGenerateEmployee",dataController.getGenerateEmployee)
router.post("/GetUserCheckIN",dataController.GetUserCheckIN)
router.post("/FetchWeekOff",dataController.FetchWeekOff)
router.post("/FetchGenerateEmployee",dataController.FetchGenerateEmployee)
router.post("/getLeaveStatus",dataController.getLeaveStatus)
router.post("/AddPMSSetting",dataController.AddPMSSetting)
router.post("/deletePMSsettings",dataController.deletePMSsettings)
router.post("/GetPMSsettings",dataController.GetPMSsettings)
router.post("/PMSsettingsUpdate",dataController.PMSsettingsUpdate)
router.post("/SettingEmployeeUpdate",dataController.SettingEmployeeUpdate)
router.post("/ESSEmployeeDashboard",dataController.ESSEmployeeDashboard)
router.post("/getAnnouncementText",dataController.getAnnouncementText)
router.post("/getManager",dataController.getManager)
router.post("/getCheckInStatus",dataController.getCheckInStatus)
router.post("/Getpayslip",dataController.Getpayslip)
router.post("/getEmployeeId", dataController.getEmployeeId)
router.post("/DashboardOverallAttendanceData", dataController.DashboardOverallAttendanceData)
router.post("/getEmployeeCheckInCheckOut", dataController.getEmployeeCheckInCheckOut)
router.post("/getTaskUserID", dataController.getTaskUserID)
router.post("/PMS_Client_infoInsert", dataController.PMS_Client_infoInsert)
router.post("/GetPaymentMode", dataController.GetPaymentMode)
router.post("/GetPaymentType", dataController.GetPaymentType)
router.post("/GetClientInfoSearch", dataController.GetClientInfoSearch)
router.post("/uploadImage", upload2.single("image"), dataController.uploadImages);
router.post("/PMS_Client_infoLoopUpdate", dataController.PMS_Client_infoLoopUpdate)
router.post("/PMS_Client_infoDelete", dataController.PMS_Client_infoDelete)
router.post("/PMS_Client_infoLoopDelete", dataController.PMS_Client_infoLoopDelete)
router.post("/PMS_Client_infoUpdate", dataController.PMS_Client_infoUpdate)
router.post("/getDateRangeCRM", dataController.getDateRangeCRM)
router.post("/getDomain", dataController.getDomain)
router.post("/PrintTemplateUpdate", dataController.PrintTemplateUpdate)
router.post("/candidate_masterLoopUpdate", dataController.candidate_masterLoopUpdate)
router.post("/candidate_masterInsert",upload.single('Canditate_CV'),dataController.candidate_masterInsert)
router.post("/candidate_masterLoopDelete", dataController.candidate_masterLoopDelete)
router.post("/PrintTemplateUpdate", dataController.PrintTemplateUpdate)
router.post("/interview_panelInsert", dataController.interview_panelInsert)
router.post("/interview_panelLoopUpdate", dataController.interview_panelLoopUpdate)
router.post("/interview_panelLoopDelete", dataController.interview_panelLoopDelete)
router.post("/job_masterInsert", dataController.job_masterInsert)
router.post("/job_masterLoopInsert", dataController.job_masterLoopInsert)
router.post("/job_masterLoopUpdate", dataController.job_masterLoopUpdate)
router.post("/job_masterLoopDelete", dataController.job_masterLoopDelete)
router.post("/interview_panel_membersInsert", dataController.interview_panel_membersInsert)
router.post("/interview_panel_membersLoopInsert", dataController.interview_panel_membersLoopInsert)
router.post("/interview_panel_membersLoopUpdate", dataController.interview_panel_membersLoopUpdate)
router.post("/interview_panel_membersLoopDelete", dataController.interview_panel_membersLoopDelete)
router.post("/interview_scheduleInsert", dataController.interview_scheduleInsert)
router.post("/interview_scheduleLoopUpdate", dataController.interview_scheduleLoopUpdate)
router.post("/interview_scheduleLoopDelete", dataController.interview_scheduleLoopDelete)
router.post("/interview_feedbackInsert", dataController.interview_feedbackInsert)
router.post("/interview_feedbackLoopUpdate", dataController.interview_feedbackLoopUpdate)
router.post("/interview_feedbackLoopDelete", dataController.interview_feedbackLoopDelete)
router.post("/interview_decisionInsert", dataController.interview_decisionInsert)
router.post("/interview_decisionLoopUpdate", dataController.interview_decisionLoopUpdate)
router.post("/interview_decisionLoopDelete", dataController.interview_decisionLoopDelete)
router.post("/CandidateSearch", dataController.CandidateSearch)
router.post("/JobmasterSearch", dataController.JobmasterSearch)
router.post("/InterviewPanel", dataController.InterviewPanel)
router.post("/InterviewPanelMembers", dataController.InterviewPanelMembers)
router.post("/InterviewSchedule", dataController.InterviewSchedule)
router.post("/InterviewFeedbackSC", dataController.InterviewFeedbackSC)
router.post("/InterviewDecisionSC", dataController.InterviewDecisionSC)
router.post("/DeptID", dataController.DeptID)
router.post("/JobMaster", dataController.JobMaster)
router.post("/InterviewPanelData", dataController.InterviewPanelData)
router.post("/ScheduleID", dataController.ScheduleID)
router.post("/CanditateID", dataController.CanditateID)
router.post("/Feedback_ID", dataController.Feedback_ID)
router.post("/Decision_ID", dataController.Decision_ID)
router.post("/Employee_ID", dataController.Employee_ID)
router.post("/InterviewMode", dataController.InterviewMode)
router.post("/InterviewStatus", dataController.InterviewStatus)
router.post("/Recommendation", dataController.Recommendation)
router.post("/TimeZonemasterInsert", dataController.TimeZonemasterInsert)
router.post("/TimeZonemasterUpdate", dataController.TimeZonemasterUpdate)
router.post("/TimeZonemasterDelete", dataController.TimeZonemasterDelete)
router.get("/getTimeZoneData",dataController.getTimeZoneData)
router.post("/getTimeZonesearchdata",dataController.getTimeZonesearchdata)
router.post("/getTitle",dataController.getTitle)
router.post("/getReligion",dataController.getReligion)
router.post("/getNationality",dataController.getNationality)
router.post("/CountryMasterInsert",dataController.CountryMasterInsert)
router.post("/getCountrySearchData",dataController.getCountrySearchData)
router.post("/Country_MasterLoopUpdate",dataController.Country_MasterLoopUpdate)
router.post("/Country_MasterLoopDelete",dataController.Country_MasterLoopDelete)
router.post("/GetCountry",dataController.GetCountry)
router.post("/Time_Zone_masterLoopUpdate",dataController.Time_Zone_masterLoopUpdate)
router.post("/CountryMasterUpdate",dataController.CountryMasterUpdate)
router.post("/Time_Zone_masterLoopDelete",dataController.Time_Zone_masterLoopDelete)
router.post("/Shift_MasterInsert",dataController.Shift_MasterInsert)
router.post("/getShiftsearchdata",dataController.getShiftsearchdata)
router.post("/sp_Shift_MasterLoopUpdate",dataController.sp_Shift_MasterLoopUpdate)
router.post("/getSex",dataController.getSex)
router.post("/getAccountType",dataController.getAccountType)
router.post("/getBool",dataController.getBoolean)
router.post("/getEmployeeType",dataController.getEmployeeType)
router.post("/getEmployeeTypeDD",dataController.getEmployeeTypeDD)
router.post("/Employment_Type_MasterInsert",dataController.Employment_Type_MasterInsert)
router.post("/Employment_Type_MasterUpdate",dataController.Employment_Type_MasterUpdate)
router.post("/Employment_Type_MasterDelete",dataController.Employment_Type_MasterDelete)
router.post("/Employment_Type_MasterLoopUpdate",dataController.Employment_Type_MasterLoopUpdate)
router.post("/Employment_Type_MasterLoopDelete",dataController.Employment_Type_MasterLoopDelete)
router.post("/Shift_Pattern_MasterInsert",dataController.Shift_Pattern_MasterInsert)
router.post("/Shift_Pattern_MasterUpdate",dataController.Shift_Pattern_MasterUpdate)
router.post("/Shift_Pattern_MasterDelete",dataController.Shift_Pattern_MasterDelete)
router.post("/Shift_Pattern_MasterLoopInsert",dataController.Shift_Pattern_MasterLoopInsert)
router.post("/Shift_Pattern_MasterLoopUpdate",dataController.Shift_Pattern_MasterLoopUpdate)
router.post("/Shift_Pattern_MasterLoopDelete",dataController.Shift_Pattern_MasterLoopDelete)
router.post("/Shift_Pattern_DetailInsert",dataController.Shift_Pattern_DetailInsert)
router.post("/Shift_Pattern_DetailUpdate",dataController.Shift_Pattern_DetailUpdate)
router.post("/Shift_Pattern_DetailDelete",dataController.Shift_Pattern_DetailDelete)
router.post("/Shift_Pattern_DetailLoopInsert",dataController.Shift_Pattern_DetailLoopInsert)
router.post("/Shift_Pattern_DetailLoopUpdate",dataController.Shift_Pattern_DetailLoopUpdate)
router.post("/Shift_Pattern_DetailLoopDelete",dataController.Shift_Pattern_DetailLoopDelete)
router.post("/Employee_shift_mappingInsert",dataController.Employee_shift_mappingInsert)
router.post("/Employee_shift_mappingUpdate",dataController.Employee_shift_mappingUpdate)
router.post("/Employee_shift_mappingDelete",dataController.Employee_shift_mappingDelete)
router.post("/Employee_shift_mappingLoopInsert",dataController.Employee_shift_mappingLoopInsert)
router.post("/Employee_shift_mappingLoopUpdate",dataController.Employee_shift_mappingLoopUpdate)
router.post("/Employee_shift_mappingLoopDelete",dataController.Employee_shift_mappingLoopDelete)
router.post("/sp_Shift_MasterLoopDelete",dataController.sp_Shift_MasterLoopDelete)
router.post("/Shift_Type_MasterInsert",dataController.Shift_Type_MasterInsert)
router.post("/getShift_TypeSC",dataController.getShift_TypeSC)
router.post("/Shift_TypeMasterDelete",dataController.Shift_TypeMasterDelete)
router.post("/ShiftPattern_Insert",dataController.ShiftPattern_Insert)
router.post("/ShiftPattern_SC",dataController.ShiftPattern_SC)
router.post("/ShiftPattern_Update",dataController.ShiftPattern_Update)
router.post("/ShiftPattern_Delete",dataController.ShiftPattern_Delete)
router.post("/Shift_TypeMasterUpdate",dataController.Shift_TypeMasterUpdate)
router.post("/ShiftPatternDetail_SC",dataController.ShiftPatternDetail_SC)
router.post("/Employment_Type_MasterSc",dataController.Employment_Type_MasterSc)
router.post("/ShiftMasterDropDown",dataController.ShiftMasterDropDown)
router.post("/ShiftTypeDropDown",dataController.ShiftTypeDropDown)
router.post("/ShiftPatternMasterDropDown",dataController.ShiftPatternMasterDropDown)
router.post("/Employee_shift_mappingSc",dataController.Employee_shift_mappingSc)
router.post("/InterviewScheduleSearch",dataController.InterviewScheduleSearch)
router.post("/InterviewFeedbackSearch",dataController.InterviewFeedbackSearch)
router.post("/InterviewProgressSearch",dataController.InterviewProgressSearch)
router.post("/PanelPerformanceSearch",dataController.PanelPerformanceSearch)
router.post("/HiringDecisionSearch",dataController.HiringDecisionSearch)
router.post("/CandidateAppliedSearch",dataController.CandidateAppliedSearch)
router.post("/getHolidayType",dataController.getHolidayType)
router.post("/TotalInterviewSchedule",dataController.TotalInterviewSchedule)
router.post("/InterviewCompletionRateSC",dataController.InterviewCompletionRateSC)
router.post("/loan_approvalsInsert",dataController.loan_approvalsInsert)
router.post("/loan_approvalsUpdate",dataController.loan_approvalsUpdate)
router.post("/loan_approvalsDelete",dataController.loan_approvalsDelete)
router.post("/loan_approvalsLoopInsert",dataController.loan_approvalsLoopInsert)
router.post("/loan_approvalsLoopUpdate",dataController.loan_approvalsLoopUpdate)
router.post("/loan_approvalsLoopDelete",dataController.loan_approvalsLoopDelete)
router.post("/loan_repayment_scheduleInsert",dataController.loan_repayment_scheduleInsert)
router.post("/loan_repayment_scheduleUpdate",dataController.loan_repayment_scheduleUpdate)
router.post("/loan_repayment_scheduleDelete",dataController.loan_repayment_scheduleDelete)
router.post("/loan_repayment_scheduleLoopInsert",dataController.loan_repayment_scheduleLoopInsert)
router.post("/loan_repayment_scheduleLoopUpdate",dataController.loan_repayment_scheduleLoopUpdate)
router.post("/loan_repayment_scheduleLoopDelete",dataController.loan_repayment_scheduleLoopDelete)
router.post("/loan_paymentsInsert",dataController.loan_paymentsInsert)
router.post("/loan_paymentsUpdate",dataController.loan_paymentsUpdate)
router.post("/loan_paymentsDelete",dataController.loan_paymentsDelete)
router.post("/loan_paymentsLoopInsert",dataController.loan_paymentsLoopInsert)
router.post("/loan_paymentsLoopUpdate",dataController.loan_paymentsLoopUpdate)
router.post("/loan_paymentsLoopDelete",dataController.loan_paymentsLoopDelete)
router.post("/getInterviewDashboardCount",dataController.getInterviewDashboardCount)
router.post("/getGenerateShift",dataController.getGenerateShift)
router.post("/getEmpShiftReport",dataController.getEmpShiftReport)
router.post("/getDepartmentDashboard",dataController.getDepartmentDashboard)
router.post("/getDepartment",dataController.getDepartment)
router.post("/getAdEmpShiftReport",dataController.getAdEmpShiftReport)
router.post("/shiftPatternChart",dataController.shiftPatternChart)
router.post("/Shift_Summary_Report",dataController.Shift_Summary_Report)
router.post("/visa_requestsInsert",dataController.visa_requestsInsert)
router.post("/visa_requestsUpdate",dataController.visa_requestsUpdate)
router.post("/visa_requestsDelete",dataController.visa_requestsDelete)
router.post("/visa_requestsLoopInsert",dataController.visa_requestsLoopInsert)
router.post("/visa_requestsLoopUpdate",dataController.visa_requestsLoopUpdate)
router.post("/visa_requestsLoopDelete",dataController.visa_requestsLoopDelete)
router.post("/travel_requestsInsert",dataController.travel_requestsInsert)
router.post("/travel_requestsUpdate",dataController.travel_requestsUpdate)
router.post("/travel_requestsDelete",dataController.travel_requestsDelete)
router.post("/travel_requestsLoopInsert",dataController.travel_requestsLoopInsert)
router.post("/travel_requestsLoopUpdate",dataController.travel_requestsLoopUpdate)
router.post("/travel_requestsLoopDelete",dataController.travel_requestsLoopDelete)
router.post("/loan_requestsInsert",dataController.loan_requestsInsert)
router.post("/loan_requestsUpdate",dataController.loan_requestsUpdate)
router.post("/loan_requestsDelete",dataController.loan_requestsDelete)
router.post("/loan_requestsLoopInsert",dataController.loan_requestsLoopInsert)
router.post("/loan_requestsLoopUpdate",dataController.loan_requestsLoopUpdate)
router.post("/loan_requestsLoopDelete",dataController.loan_requestsLoopDelete)
router.post("/getVisaType",dataController.getVisaType)
router.post("/travel_requestsSearch",dataController.travel_requestsSearch)
router.post("/visaRequestSearch",dataController.visaRequestSearch)
router.post("/loan_documentsInsert",upload.single('document'),dataController.loan_documentsInsert);
router.post("/loan_documentsDelete",dataController.loan_documentsDelete)
router.post("/loan_documentsLoopInsert",dataController.loan_documentsLoopInsert)
router.post("/loan_documentsLoopUpdate",dataController.loan_documentsLoopUpdate)
router.post("/loan_documentsLoopDelete",dataController.loan_documentsLoopDelete)
router.post("/getLoanTypes",dataController.getLoanTypes)
router.post("/loanRequestSearch",dataController.loanRequestSearch)
router.post("/getLoanRequest",dataController.getLoanRequest)
router.post("/loan_approvalsSearch",dataController.loan_approvalsSearch)
router.post("/getPaymentMethod",dataController.getPaymentMethod)
router.post("/getLoanRequest",dataController.getLoanRequest)
router.post("/loanPaymentSearch",dataController.loanPaymentSearch)
router.post("/getPaymentStatus",dataController.getPaymentStatus) 
router.post("/loanScheduleSearch",dataController.loanScheduleSearch)
router.post("/loan_status_historyInsert", dataController.loan_status_historyInsert)
router.post("/loan_status_historyUpdate", dataController.loan_status_historyUpdate)
router.post("/loan_status_historyDelete", dataController.loan_status_historyDelete)
router.post("/loan_status_historyLoopInsert", dataController.loan_status_historyLoopInsert)
router.post("/loan_status_historyLoopUpdate", dataController.loan_status_historyLoopUpdate)
router.post("/loan_status_historyLoopDelete", dataController.loan_status_historyLoopDelete)
router.post("/GetLoanStatus", dataController.GetLoanStatus)
router.post("/loan_documentsSearch",dataController.loan_documentsSearch)
router.post("/getApprovalLoanRequest",dataController.getApprovalLoanRequest)
router.post("/loan_status_history_search",dataController.loan_status_history_search)
router.post("/getCurrenyCode",dataController.getCurrenyCode)
router.post("/EmployeeDetailsRequest", upload.single('Photos'),dataController.EmployeeDetailsRequest) 
router.post("/AcademicDetailsRequest",dataController.AcademicDetailsRequest)
router.post("/LoanRequestDashboard",dataController.LoanRequestDashboard) 
router.post("/visaRequestDashboard",dataController.visaRequestDashboard) 
router.post("/travelRequestsDashboard",dataController.travelRequestsDashboard) 
router.post("/DashboardEmployeeInfoChange",dataController.DashboardEmployeeInfoChange) 
router.post("/ApprovalLoan",dataController.ApprovalLoan) 
router.post("/ApprovalVisa",dataController.ApprovalVisa) 
router.post("/ApprovalTravel",dataController.ApprovalTravel) 
router.post("/ApprovalPersonalInfo",dataController.ApprovalPersonalInfo) 
router.post("/FamilyDetailRequest",dataController.FamilyDetailRequest) 
router.post("/DashboardFamilyDetailChange",dataController.DashboardFamilyDetailChange) 
router.post("/ApprovalAcademicInfo",dataController.ApprovalAcademicInfo) 
router.post("/getEmployeeLeaveReport",dataController.getEmployeeLeaveReport) 
router.post("/ApprovalFamilyDetail",dataController.ApprovalFamilyDetail) 
router.post("/usercode",dataController.getUsercode)
router.post("/AcademicRequestHdr",dataController.AcademicRequestHdr)
router.post("/AcademicRequestDetails",dataController.AcademicRequestDetails)
router.post("/GetAcademicRequestDetails",dataController.GetAcademicRequestDetails)
router.post("/ApproveAcademicRequest",dataController.ApproveAcademicRequest)
router.post("/PersonalRequestDetails",dataController.PersonalRequestDetails)
router.post("/PersonalRequestHdr",dataController.PersonalRequestHdr)
router.post("/ApprovePersonalRequest",dataController.ApprovePersonalRequest)
router.post("/GetPersonalRequestDetails",dataController.GetPersonalRequestDetails)
router.post("/FamilyRequestHdr",dataController.FamilyRequestHdr)
router.post("/GetFamilyRequestDetails",dataController.GetFamilyRequestDetails)
router.post("/ApproveFamilyRequest",dataController.ApproveFamilyRequest)
router.post("/FamilyRequestDetails",dataController.FamilyRequestDetails)
router.post("/DocumentRequestDetails",dataController.DocumentRequestDetails)
router.post("/GetDocumentsRequestDetails",dataController.GetDocumentsRequestDetails)
router.post("/ApproveDocumentRequest",dataController.ApproveDocumentRequest)
router.post("/DocumentRequestHdr",dataController.DocumentRequestHdr)
router.post("/EmployeeAssetsInsert", dataController.EmployeeAssetsInsert)
router.post("/EmployeeAssetsUpdate", dataController.EmployeeAssetsUpdate)
router.post("/EmployeeAssetsDelete", dataController.EmployeeAssetsDelete)
router.post("/EmployeeAssetsLoopInsert", dataController.EmployeeAssetsLoopInsert)
router.post("/EmployeeAssetsLoopUpdate", dataController.EmployeeAssetsLoopUpdate)
router.post("/EmployeeAssetsLoopDelete", dataController.EmployeeAssetsLoopDelete)
router.post("/LoanTypeIdDropDown",dataController.LoanTypeIdDropDown)
router.post("/GetLoanSummaryReport",dataController.GetLoanSummaryReport)
router.post("/GetPendingApprovalsReport",dataController.GetPendingApprovalsReport)
router.post("/GetLoanDisbursementReport",dataController.GetLoanDisbursementReport)
router.post("/getRequestStatus", dataController.getRequestStatus)
router.post("/GetOverdueLoansReport", dataController.GetOverdueLoansReport)
router.post("/GetRepaymentScheduleReport", dataController.GetRepaymentScheduleReport)
router.post("/getAssetSearchCretria", dataController.getAssetSearchCretria)
router.post("/getEmployeeAssets",dataController.getEmployeeAssets)
router.post("/GetDashboardAttendanceSummary",dataController.GetDashboardAttendanceSummary)
router.post("/LoanTypeDistribution",dataController.LoanTypeDistribution)
router.post("/DepartmentLoanAmount",dataController.DepartmentLoanAmount)
router.post("/LoanStatusTrend",dataController.LoanStatusTrend)
router.post("/OverduevsPaid",dataController.OverduevsPaid)
router.post("/getTHRSReport",dataController.getTHRSReport)
router.post("/EmployeeAssets_HdrInsert",dataController.EmployeeAssets_HdrInsert)
router.post("/EmployeeAssets_HdrLoopInsert",dataController.EmployeeAssets_HdrLoopInsert)
router.post("/EmployeeAssets_HdrLoopUpdate",dataController.EmployeeAssets_HdrLoopUpdate)
router.post("/EmployeeAssets_SC",dataController.EmployeeAssets_SC)
router.post("/EmployeeAssets_HdrLoopDelete",dataController.EmployeeAssets_HdrLoopDelete)
router.post("/AssetIDDropoption", dataController.AssetIDDropoption)
router.post("/LeaveCancellation", dataController.LeaveCancellation)
router.post("/getAllocationStatus", dataController.getAllocationStatus)
router.post("/compOffRequestInsert", dataController.compOffRequestInsert)
router.post("/DashboardCompOffRequest", dataController.DashboardCompOffRequest)
router.post("/DashboardCompOffApproval", dataController.DashboardCompOffApproval)
router.post("/getCompOffDropdown", dataController.getCompOffDropdown)
router.post("/AssetRequestHdr", dataController.AssetRequestHdr)
router.post("/GetAssetRequestDetails", dataController.GetAssetRequestDetails)
router.post("/ApproveAssetRequest", dataController.ApproveAssetRequest)
router.post("/AssetRequestDetails", dataController.AssetRequestDetails)
router.post("/AddPayrollSetting",dataController.AddPayrollSetting)
router.post("/UpdatePayrollSetting",dataController.UpdatePayrollSetting)
router.post("/DeletePayrollSetting",dataController.DeletePayrollSetting)
router.post("/GetPayrollSettings",dataController.GetPayrollSettings)
router.post("/payroll_settingsSearch",dataController.payroll_settingsSearch)
router.post("/UpdatePayrollSettings",dataController.UpdatePayrollSettings)
router.post("/getdocument_type",dataController.getdocument_type)
router.post("/PendingAssetRequests_SC",dataController.PendingAssetRequests_SC)
router.post("/EmpCompOffList",dataController.EmpCompOffList)
router.post("/compOffSearchCriteria",dataController.compOffSearchCriteria)
router.post("/compOffRequestReport",dataController.compOffRequestReport)
router.post("/AssetIDDrop",dataController.AssetIDDrop)
router.post("/getTransportMode",dataController.getTransportMode)
router.post("/AssetLifecycleReport_AS",dataController.AssetLifecycleReport_AS)
router.post("/EmployeeAssetReport_EAR",dataController.EmployeeAssetReport_EAR)
router.post("/GetAbsentReport",dataController.GetAbsentReport)
router.post("/GetLateReport",dataController.GetLateReport)
router.post("/GetOvertimeReport",dataController.GetOvertimeReport) 
router.post("/LeaveSummaryDrop",dataController.LeaveSummaryDrop) 
router.post("/getUCN",dataController.getUCN)
router.post("/getDateFormat",dataController.getDateFormat)
router.post("/global_settingsInsert",dataController.global_settingsInsert)
router.post("/EmpDepartment",dataController.EmpDepartment)
router.post("/approvalLoanRequestSearch",dataController.approvalLoanRequestSearch)
router.post("/getSettings",dataController.getSettings)
router.post("/GetJobID", dataController.GetJobID)
router.post("/GetLoanTypeID", dataController.GetLoanTypeID)
router.post("/shiftChangeRequestInsert",dataController.shiftChangeRequestInsert)
router.post("/shiftChangeRequestEmployee",dataController.shiftChangeRequestEmployee)
router.post("/shiftRequestEmployeeApproval",dataController.shiftRequestEmployeeApproval)
router.post("/getAllDesgination",dataController.getAllDesgination)
router.post("/deletePrintTemplates",dataController.deletePrintTemplates)
router.post("/shiftChangeRequestManager",dataController.shiftChangeRequestManager)
router.post("/shiftRequestManagerApproval",dataController.shiftRequestManagerApproval)
router.post("/getLoanDashboard",dataController.getLoanDashboard)
router.post("/getAGES",dataController.getAGES)
router.post("/getAGESTypes",dataController.getAGESTypes)
router.post("/shiftChangeRequestSearch",dataController.shiftChangeRequestSearch)
router.post("/shiftChangeRequestReport",dataController.shiftChangeRequestReport)
router.post("/LoanTypeIdDetails",dataController.LoanTypeIdDetails)
router.post("/monthlyInstallmentCalculation",dataController.monthlyInstallmentCalculation)
router.post("/getLoanNotification",dataController.getLoanNotification)
router.post("/loanNotificationSeen",dataController.loanNotificationSeen)
router.post("/getLeaveNotification",dataController.getLeaveNotification)
router.post("/leaveNotificationSeen",dataController.leaveNotificationSeen)
router.post("/getVisaNotification",dataController.getVisaNotification)
router.post("/visaNotificationSeen",dataController.visaNotificationSeen)
router.post("/getTravelNotification",dataController.getTravelNotification)
router.post("/travelNotificationSeen",dataController.travelNotificationSeen)
router.post("/getComOffNotification",dataController.getComOffNotification)
router.post("/compOffNotificationSeen",dataController.compOffNotificationSeen)
router.post("/getShiftNotification",dataController.getShiftNotification)
router.post("/shiftNotificationSeen",dataController.shiftNotificationSeen)
router.post("/GetPersonalRequest",dataController.GetPersonalRequest)
router.post("/GetFamilyRequest",dataController.GetFamilyRequest)
router.post("/GetAcademicRequest",dataController.GetAcademicRequest)
router.post("/GetDocumentsRequest",dataController.GetDocumentsRequest)
router.post("/GetAssetRequest",dataController.GetAssetRequest)
router.post("/visaCancellation",dataController.visaCancellation)
router.post("/travelCancellation",dataController.travelCancellation)
router.post("/getFEM",dataController.getFEM)
router.post("/getMappedEmployeeDropdown",dataController.getMappedEmployeeDropdown)
router.post("/getCompanyData",dataController.getCompanyData)
router.post("/getCompanyMappingData",dataController.getCompanyMappingData)
router.post("/getLocationData",dataController.getLocationData)
router.post("/getRoleData",dataController.getRoleData)
router.post("/getRoleMappingData",dataController.getRoleMappingData)
router.post("/getRoleRightsData",dataController.getRoleRightsData)
router.post("/getUserData",dataController.getUserData)
router.post("/getAttributeData",dataController.getAttributeData)
router.post("/getBankAccountData",dataController.getBankAccountData)
router.post("/getDepartmentData",dataController.getDepartmentData)
router.post("/getDesignationData",dataController.getDesignationData)
router.post("/getIntermediaryData",dataController.getIntermediaryData)
router.post("/getNumberSeriesData",dataController.getNumberSeriesData)
router.post("/getWarehouseData",dataController.getWarehouseData)
router.post("/getFinancialYearAccessData",dataController.getFinancialYearAccessData)
router.post("/getDefaultScreens",dataController.getDefaultScreens)
router.post("/GetCheckInMode",dataController.GetCheckInMode)
router.post("/getDefaultUserCompany",dataController.getDefaultUserCompany)
router.post("/userSettingsInsert",dataController.userSettingsInsert)
router.post("/getUserSettings",dataController.getUserSettings)




module.exports = router;
